### ISSUE TITLE
Missing Agencies

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [ODOT-PTS/TNAST_MAVEN#90]
I reviewed the agencies that are contained in the April 2018 DB, and noted a few major changes from the September 2017 DB. 

Contains 58 of 64 Agencies.

Missing: **C-Tran**, Curry Public Transit, **LTD**, Pacific Transit, Sage Stage, **RVTD**, **Cherriots**
Changed Name: Pacific Crest became Eugene to Bend, 
Added Oregon Express Shuttle

It looks like three agencies that serve parts of Oregon but are based in other states got omitted(Sage State, Pacific Transit and C-Tran), along with three of the largest agencies in the state (Cherriots, Lane Transit District and Rogue Valley Transportation District) and Curry Public Transit.

The feeds for the agencies above can be found at http://www.oregon-gtfs.com, and should be added to the most recent snapshot, with input from @antrim.

**Comment by KalonThomas** [comment]
Updated agencies list with data url locations can be found here: https://docs.google.com/spreadsheets/d/1Pq2vGSW3ba_Y-xvf80aIcB8dim6c6wr_-JnawyJGm7k/edit#gid=1538882271

**Comment by irees** [comment]
These will be included in the next development server build.

**Comment by irees** [comment]
Updated build based on http://oregon-gtfs.com/gtfs_data/pacificcrest-or-us/pacificcrest-or-us.zip

Note: A few feeds failed to import (Columbia Gorge Express, Linn Benton Loop, Quail Trail Public Transit, Sandy Area Metro, Sunset Empire Transportation District, and The Wave) due to some hibernate uniqueness constraint violation. I'm looking into it and will figure out if it's in my code or in the data.

**Comment by irees** [comment]
Moving the feed import issue to #99.
